image: node:22

pages:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never # No runners will run on branches other than main
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
